# Generated by Django 5.0.3 on 2026-03-31 15:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('has_plan', models.BooleanField(default=False)),
                ('kirvano_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_status', models.CharField(blank=True, choices=[('active', 'Ativo'), ('canceled', 'Cancelado'), ('overdue', 'Atrasado'), ('expired', 'Expirado')], max_length=50, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateTimeField(blank=True, null=True)),
                ('welcome_message_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
